name: expense_tracker_app
description: A simple expense tracker using Flutter and SQFlite
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  intl: ^0.17.0
  flutter_slidable: ^3.0.0
  syncfusion_flutter_charts: ^20.2.44

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true